import type { Metadata } from 'next'
import ConfigureAmplifyClientSide from '@/app/components/ConfigureAmplifyForClient'
import './globals.css'
import '@aws-amplify/ui-react/styles.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<ConfigureAmplifyClientSide />
				{children}
			</body>
		</html>
	)
}
